name: zerotopandas
channels:
  - defaults
dependencies:
  - ca-certificates=2020.7.22
  - certifi=2020.6.20
  - libcxx=10.0.0
  - libedit=3.1.20191231
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1h
  - pip=20.2.2
  - python=3.8.5
  - readline=8.0
  - setuptools=49.6.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.35.1
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - appnope==0.1.0
    - argon2-cffi==20.1.0
    - async-generator==1.10
    - attrs==20.2.0
    - backcall==0.2.0
    - bleach==3.2.1
    - cffi==1.14.3
    - chardet==3.0.4
    - click==7.1.2
    - cycler==0.10.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - idna==2.10
    - ipykernel==5.3.4
    - ipython==7.18.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.2
    - jinja2==2.11.2
    - jovian==0.2.26
    - json5==0.9.5
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==6.1.7
    - jupyter-console==6.2.0
    - jupyter-contrib-core==0.3.3
    - jupyter-core==4.6.3
    - jupyter-nbextensions-configurator==0.4.1
    - jupyterlab==2.2.9
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==1.2.0
    - kiwisolver==1.2.0
    - markupsafe==1.1.1
    - matplotlib==3.3.3
    - mistune==0.8.4
    - nbclient==0.5.0
    - nbconvert==6.0.6
    - nbformat==5.0.7
    - nest-asyncio==1.4.1
    - notebook==6.1.4
    - numpy==1.19.4
    - opendatasets==0.1.0
    - packaging==20.4
    - pandas==1.1.4
    - pandoc==1.0.2
    - pandocfilters==1.4.2
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==7.2.0
    - ply==3.11
    - prometheus-client==0.8.0
    - prompt-toolkit==3.0.7
    - ptyprocess==0.6.0
    - pycparser==2.20
    - pygments==2.7.1
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-dateutil==2.8.1
    - pytz==2020.1
    - pyyaml==5.3.1
    - pyzmq==19.0.2
    - qtconsole==4.7.7
    - qtpy==1.9.0
    - requests==2.24.0
    - scipy==1.5.2
    - seaborn==0.11.0
    - send2trash==1.5.0
    - six==1.15.0
    - terminado==0.9.1
    - testpath==0.4.4
    - tornado==6.0.4
    - tqdm==4.50.0
    - traitlets==5.0.4
    - urllib3==1.25.10
    - uuid==1.30
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
prefix: /Users/aakashns/miniconda3/envs/zerotopandas

